layout_spectrum: 0.7022620965726674
typography_spectrum: 0.71053436701186
color:
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  brandStrength: 0.9681929729413241
  lightness: 0.5786888988222927
  saturation: 0.7642908054403961
  rhythmicContrast: 0.16774670034646988
name: seancronin2
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
